# Generated by Django 3.0.6 on 2021-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
