# Generated by Django 3.0.6 on 2021-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210226_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
