# Generated by Django 3.0.6 on 2021-02-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_invoice_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fullname',
        ),
    ]
