# Generated by Django 3.0.6 on 2021-03-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_invoicepdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepdf',
            name='slug',
        ),
    ]
