# Generated by Django 3.0.6 on 2021-03-01 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_invoicepdf_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepdf',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
