# Generated by Django 3.0.6 on 2021-03-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210301_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepdf',
            old_name='pdff',
            new_name='mypdf',
        ),
    ]
