# Generated by Django 3.0.6 on 2021-03-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepdf',
            name='slug',
        ),
    ]
