# Generated by Django 2.1.11 on 2021-03-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_invoicepdf_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst',
            field=models.IntegerField(default=0),
        ),
    ]
